SOURCES      = src/*.cpp
TRANSLATIONS += locales/ytdl-gui_fr.ts
TRANSLATIONS += locales/ytdl-gui_de.ts
TRANSLATIONS += locales/ytdl-gui_es.ts
TRANSLATIONS += locales/ytdl-gui_eo.ts
TRANSLATIONS += locales/ytdl-gui_et.ts
TRANSLATIONS += locales/ytdl-gui_zh_Hans.ts
TRANSLATIONS += locales/ytdl-gui_nl.ts
TRANSLATIONS += locales/ytdl-gui_kab.ts # not recognized by lupdate, you need to change the language code in ytdl-gui_kab.ts to another one when updating
FORMS        += src/*.ui
